import glob
from pathlib import Path
from collections import defaultdict
import re
import math

import numpy as np
import pandas as pd

NUM_COLUMNS = 4

print("<!-- THIS README IS AUTOGENERATED, DO NOT MODIFY IT DIRECTLY -->")
with open("readme_preamble.md") as preamble:
    print(preamble.read())

print("## Table of Contents")

emojis_by_category = defaultdict(list)
for emoji_path in sorted(glob.glob("emojis/*/*", recursive=True)):
    path = Path(emoji_path)
    category = path.parts[1]

    escaped_emoji_path = emoji_path.replace(" ", "%20")
    image_url = f"https://raw.githubusercontent.com/kevinwuhoo/slackmojis/main/{escaped_emoji_path}"
    image = f"<img src='{image_url}' width='128px' />"
    name = path.stem

    cell = f"{image}<br /><code>{name}</code>"

    emojis_by_category[category].append(cell)

# table of contents
for category in emojis_by_category.keys():
    # remove non-alphanumeric characters and substitute space for hyphen
    markdown_category = re.sub(r"[^\w]", "", category.replace(" ", "-").lower())
    print(f"- [{category}](#{markdown_category})")


for category, slackmojis in emojis_by_category.items():
    print(f"\n## {category}")

    # create a 2d array in the shape of the table
    # convert it to markdown
    padded_slackmojis = np.append(
        slackmojis,
        [""] * ((NUM_COLUMNS - (len(slackmojis) % NUM_COLUMNS)) % NUM_COLUMNS),
    )
    slackmoji_grid = padded_slackmojis.reshape(-1, NUM_COLUMNS)
    print(pd.DataFrame(slackmoji_grid).to_html(header=False, index=False, escape=False))
